#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Browser

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export GOPATH=$GOPATH:~/fury_afip/
export PATH="$PATH:$HOME/.scripts/bin/:$HOME/.npm-global/bin:$GOPATH/bin"
export GOPATH="$HOME/.go/"

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
    export TERM=xterm-256color
else 
    export GOPATH="$HOME/.go"
    export TERMINAL='xfce4-terminal'
    export PATH=$PATH:~/.gem/ruby/2.4.0/bin/ 
    export PATH=$PATH:~/.cabal/bin/
    export PATH=$PATH:/usr/local/go/bin
fi

# Editors

# Language

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Paths

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# Aliases
alias vim="/usr/local/Cellar/vim/8.0.0502/bin/vim" # stupid mac 
alias ls='/usr/local/bin/gls --color  -h --group-directories-first -F' # stupid mac 
alias vsplit="osascript ~/.dotfiles/iterm/vsplit"
alias split="osascript ~/.dotfiles/iterm/split"
alias emacs="/usr/local/Cellar/emacs/25.2/Emacs.app/Contents/MacOS/Emacs"
alias google-chrome-stable="open -a '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'"


# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
