#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Default applications
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export TERMINAL='gnome-terminal'

# Paths and settings for developing
#
## Custom scripts
export PATH="$PATH:$HOME/.bin"

## Golang
export GOPATH="$HOME/.go"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/go/bin"

## Node / JS / NPM
export NODE_PATH="$HOME/.npm-gobal"
export PATH="$PATH:$HOME/.npm-global/bin"

## Ruby
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="$PATH:~/.gem/ruby/2.4.0/bin/"
export PATH="$PATH:$HOME/.rvm/bin"

## Haskell / Cabal
export PATH="$PATH:~/.cabal/bin/"

## Java / Groovy / Grails
export GRAILS_HOME="$HOME/.grails/grails-2.4.5/"
export PATH=$PATH:"$GRAILS_HOME/bin"
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi


# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
