#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH=$PATH:~/.scripts/bin/
export PATH=$PATH:~/.npm-global/bin/
export PATH=$PATH:~/.gem/ruby/2.4.0/bin/
export PATH=$PATH:~/.cabal/bin/

export TERM=xterm-256color
export VISUAL=vim
export EDITOR=vim
export PAGER=less
