#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#clone and install dependencies

# GNOME TERMINAL COLORS
tmpFolder="/tmp/base16-gnome-terminal"
destFolder="$HOME/.config/base16-gnome-terminal"
if [[ ! -d "$destFolder" ]]; then
    git clone https://github.com/chriskempson/base16-gnome-terminal $tmpFolder/
    mkdir "$destFolder/"
    mv "$tmpFolder/base16-chalk.dark.sh" "$destFolder/base16-chalk.dark.sh"
    $(chmod +x $destFolder/base16-chalk.dark.sh)
    $($destFolder/base16-chalk.dark.sh)
    rm -rf $tmpFolder/
else 
    echo "Looks like you've already got base16-gnome-terminal"
    echo "If that's not the case, check what's in $destFolder"
fi

base16_shell_dir="$HOME/.config/base16-shell"
if [[ ! -d  "$base16_shell_dir" ]]; then 
    git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
    $(chmod +x ~/.config/base16-shell/*)
else
    echo "Looks like you've already got base16-shell"
    echo "If that's not the case, check what's in $base16_shell_dir"
fi

echo "THIS WILL REMOVE ALL YOUR VIM, BASH, ZSH/ZPREZTO AND RANGER CONFIGS"
echo "Press Ctrl+C to quit now, or Enter to continue"
read -p ""

#vim
echo 'installing vundle and symlinking vim config'
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -sf ${BASEDIR}/vim/.vim ~/.vim
ln -sf ${BASEDIR}/vim/.vimrc ~/.vimrc

#i3
echo 'symlinking i3 config. i need to remove your ~/.i3'
ln -sf ${BASEDIR}/i3/.i3 ~/.i3
ln -sf ${BASEDIR}/i3/.i3status.conf ~/.i3status.conf

#ranger
echo 'symlinking ranger config. I need to remove ~/.config/ranger'
ln -sf ${BASEDIR}/ranger/ ~/.config/ranger

#zsh
echo 'symlinkgin zsh prezto. I need to remove ~/.zprezto'
ln -sf ${BASEDIR}/zsh/zprezto ~/.zprezto
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

#wallpapers randomizer
echo "setting up a random wallpaper from you <3"
$(chmod +x "$BASEDIR/wall-randomizer.sh")
$($BASEDIR/wall-randomizer.sh)
