#!/bin/zsh

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Hi! Welcome."
echo "Plase remember, some things here are not perfect :)"

read "yn?Continue? [yN]"
if [[  "$yn" != "y"  ]] ; then
    echo "Bye!"
    exit 0
fi

read "yn?Set up xmodmap capstoescape on .profile: [yN] \n"
if [[  "$yn" == "y"  ]] ; then
    echo "xmodmap ${BASEDIR}/capstoescape" >> ${HOME}/.profile
    echo "xmodmap ${BASEDIR}/capstoescape" >> ${HOME}/.zprofile
fi

read "yn?Are you on some version of Debian/Ubuntu: [yN]\n"
if [[  "$yn" == "y"  ]] ; then
    echo 'installing some things we will need'
    sudo apt install curl
    curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
    sudo add-apt-repository ppa:mmstick76/alacritty
    sudo apt update
    sudo apt install git vim-gtk3 emacs feh xsel tree nmap spotify-client alacritty
fi

#vim
read "yn?Configure vim [yN]\n"
if [[  "$yn" == "y"  ]] ; then
    echo 'installing vundle and symlinking vim config'
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    ln -sf ${BASEDIR}/vim/.vim ~/.vim
    ln -sf ${BASEDIR}/vim/.vimrc ~/.vimrc
    vim -E -c PluginInstall -c q
    mkdir $HOME/.swp-folder
fi

read "yn?Configure spacemacs [yN]\n"
if [[  "$yn" == "y"  ]] ; then
    echo 'installing spacemacs and copying config'
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    ln -sf ${BASEDIR}/emacs/.spacemacs ${HOME}/.spacemacs
fi

#zsh
read "yn?Configure zprezto: [yN]\n" 
if [[ "$yn" == "y" ]] ; then
    echo 'symlinkgin zsh prezto. I need to remove ~/.zprezto'
    ln -sf ${BASEDIR}/zsh/zprezto ~/.zprezto
    setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
fi

# i3
read "yn?Configure i3: [yN]\n" 
if [[ "$yn" == "y" ]] ; then
    echo 'symlinking i3 config. i need to remove your ~/.i3'
    ln -sf ${BASEDIR}/i3/.i3 $HOME/.config/i3/config
    ln -sf ${BASEDIR}/i3/.i3/statusbar $HOME/.config/i3/statusbar
    ln -sf ${BASEDIR}/i3/.i3status.conf $HOME/.config/i3/i3status.conf
fi

read "yn?Install base16 shell colors: [yN]\n" 
if [[ "$yn" == "y" ]] ; then
    echo "This is maybe a bit buggy but it kinda should work"
    base16_shell_dir="$HOME/.config/base16-shell"
    if [[  ! -d  "$base16_shell_dir"  ]] ; then 
        git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
        $(chmod +x $HOME/.config/base16-shell/*)
        $HOME/.config/base16-shell/base16_chalk
    else
        echo "Looks like you've already got base16-shell"
        echo "If that's not the case, check what's in $base16_shell_dir"
    fi
fi

#wallpapers randomizer
read "yn?Set up wallpaper automation with feh: [yN]\n" yn
if [[ "$yn" == "y" ]] ; then
    echo "setting up a random wallpaper from you <3"
    $(chmod +x "$BASEDIR/wall-randomizer.sh")
    $($BASEDIR/wall-randomizer.sh)
fi
